# Dockerfile for running org-grep. This is to make it convenient to test searcher in
# the same network as a production environment.
#
# $ docker build -f Dockerfile.org-grep -t org-grep .
# $ docker run --rm=true org-grep github.com/sourcegraph/go-langserver vscode
FROM python:3-alpine@sha256:cbfcea228e685aa3684f7a4e19be4805e3bf766f2158a4e3a54443cb608c1760

RUN pip install requests==2.18.4

COPY org-grep.py /org-grep.py

ENTRYPOINT ["python", "/org-grep.py"]
